### ISSUE TITLE
unable run The Contact Backend Server

### ISSUE THREAD

**Issue by pohand** [udacity/reactnd-issues#55]
I can not start the contact back end server when I run node server.js. There is an error with line 54 in server.js file
After that the error is
SyntaxError: Inexpected token {
at exports.runInThisContect(vm.js:53:16)
at Module._compile (module.js:404:25)
at Object.Module._extensions..js (module.js:432:10)
at Module.load(module.js:356:32)
at Function.Module._load (module.js:313:12)
at Function.module.runMain(module.js:457:10)
at startup (node.js:138:18)
at node.js:974:3

**Comment by pohand** [comment]
It seems the problem from my node.js installed in my computer. I removed it and installed new one. It works now

**Comment by hbkwong** [comment]
Thanks for checking in! If you run into further issues, feel free to reach out too. I'll keep an eye on Slack to make sure this isn't a persistent, common issue.
